---
- name: Gather service facts
  tags:
    - always
  ansible.builtin.service_facts:
- name: Enabled rules in firewalld
  become: true
  tags:
    - accessports
  ansible.builtin.firewalld:
    port: "{{ port_item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ firewall_access_port }}"
  loop_control:
    loop_var: port_item
  when:
    - ansible_facts.services is defined
    - "'firewalld.service' in ansible_facts.services"
